version: "3.3"
services: 
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes: 
            - ./client:/app
        ports: 
            - "8080:8080"
        networks: 
            - itui
    server:
        build: 
            context: ./server
            dockerfile: Dockerfile
        volumes: 
            - ./server:/app
        ports: 
            - "3000:3000"
        networks: 
            - itui
        depends_on: 
            - "db"
    db:
        build:
            context: ./postgres
            dockerfile: Dockerfile
        environment:
            POSTGRES_PASSWORD: Knife444!
            POSTGRES_DB: itui
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d/    
        ports: 
           - "5432:5432"
        networks: 
            - itui
    redis:
        build:
            context: ./redis
            dockerfile: Dockerfile 
        ports: 
           - "6379:6379"
        networks: 
            - itui
networks: 
    itui: 
        name: itui
        driver: bridge
        driver_opts:
          com.docker.network.bridge.name: itui
        